import "core-js/es/array/at";
import cloneDeep from "lodash/cloneDeep";
import {
  attribute,
  hashKey,
  autoGeneratedHashKey,
  rangeKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";
import { embed } from "@aws/dynamodb-data-mapper";

import * as model from "./model";
import { Bank, PlayArea, CardPile, CardEffectBase } from "./model";
import DrawCardPile from "./drawcardpile";
import Match from "./match";

export default class MatchState {
  @attribute({ memberType: embed(Bank), valueConstructor: Bank })
  banks: Array<Bank>;

  @attribute()
  playArea: PlayArea;

  @attribute()
  currentPlayerIndex: number;

  @attribute()
  drawPile: DrawCardPile;

  @attribute()
  discardPile: CardPile;

  @attribute()
  private _pendingEffect: CardEffectBase; //-- e.g. Kraken, Hook

  get pendingEffect(): CardEffectBase {
    return this._pendingEffect;
  }

  clearPendingEffect() {
    delete this._pendingEffect;
  }

  addPendingEffect(effect: CardEffectBase): void {
    if (this._pendingEffect) {
      throw new Error("Effect already in action: " + this._pendingEffect + " cannot add next one");
    }

    this._pendingEffect = effect;
  }

  static clone(instance: MatchState) {
    //const source = structuredClone(this); // available in node 17, from LT update in 22'Oct
    //const copy = Object.create(Object.getPrototypeOf(source)) as MatchState;
    //const copy = utils.deepCopy<MatchState>(instance);
    const copy = cloneDeep(instance);
    return copy;
  }
}
