import "core-js/es/array/at";
/* tslint:disable:max-classes-per-file */
import {
  attribute,
  hashKey,
  autoGeneratedHashKey,
  rangeKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";
import { embed } from "@aws/dynamodb-data-mapper";

import * as utils from "../utils";

export const OCardSuit = {
  Anchor: 0,
  Hook: 1,
  Cannon: 2,
  Key: 3,
  Chest: 4,
  Map: 5,
  Oracle: 6,
  Sword: 7,
  Kraken: 8,
  Mermaid: 9,
}; // as const;
export type CardSuit = keyof typeof OCardSuit;
// export type Suit = typeof OSuit[keyof typeof OSuit];
// export type Suit =
//   | "Anchor"
//   | "Hook"
//   | "Cannon"
//   | "Key"
//   | "Chest"
//   | "Map"
//   | "Oracle"
//   | "Sword"
//   | "Kraken"
//   | "Mermaid";

export type CardValueBase = 2 | 3 | 4 | 5 | 6 | 7;
export type CardValue = CardValueBase | 8 | 9;
export type CardAbbreviation = [CardSuit, CardValue];
export class Card {
  //TODO: change to tuple
  @attribute()
  suit: CardSuit;

  @attribute()
  value: CardValue;

  constructor(suit?: CardSuit, value?: CardValue) {
    this.suit = suit;
    this.value = value;
  }
  static fromAbbreviation(abbreviation: CardAbbreviation) {
    return new Card(abbreviation[0], abbreviation[1]);
  }
}

export class CardPile {
  @attribute({ memberType: embed(Card) })
  readonly cards: Array<Card>;
  //-- architecture warning - should not derive from Array<Card> directly as lodash Lodash only clones index values (and some meta values) of arrays.
  constructor() {
    this.cards = new Array<Card>();
  }
  get length(): number {
    return this.cards.length;
  }
  set length(value: number) {
    this.cards.length = value;
  }
}
export class CardSuitStack {
  stack: Set<CardValue>;
  constructor() {
    this.stack = new Set<CardValue>();
  }

  max() {
    return Math.max.apply(null, Array.from(this.stack.values()));
  }
}
export class OrderedCardPile {
  constructor() {
    this.piles = new Map<CardSuit, CardSuitStack>();
  }

  @attribute({ memberType: embed(CardSuitStack) })
  piles: Map<CardSuit, CardSuitStack>;

  get flatSize(): number {
    let count = 0;
    for (let [key, value] of this.piles.entries()) count += value.stack.size;
    return count;
  }
}

export class Bank extends OrderedCardPile {}

export class PlayArea extends CardPile {} // or Map<Suit, number>;

export type EffectPointer = {
  moveIndex: number;
  eventIndex: number;
};

export { default as DrawCardPile } from "./drawcardpile";
export { default as MatchState } from "./matchstate";
export { default as Match, MatchId } from "./match";
export { default as Move, MoveId } from "./move";
export { default as Player, PlayerId } from "./player";
export * from "./matchevent";
export * from "./cardeffect";
