import "core-js/es/array/at";
import {
  attribute,
  hashKey,
  autoGeneratedHashKey,
  rangeKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";
import { embed } from "@aws/dynamodb-data-mapper";

import * as utils from "../utils";
import DrawCardPile from "./drawcardpile";
import MatchState from "./matchstate";
import { MatchEventBase } from "./matchevent";
import Match, { MatchId } from "./match";

export type MoveId = string;

@table("Moves")
export default class Move {
  @autoGeneratedHashKey()
  id!: MoveId;

  @rangeKey({ type: "String" })
  matchId!: MatchId; //-- parent matchid

  @attribute()
  sequenceId: number;

  // @attribute({
  //   marshall: utils.dateMarshall,
  //   unmarshall: utils.dateUnmarshall,
  //   defaultProvider: () => new Date().toISOString(),
  // })
  @attribute({
    type: "Date",
    defaultProvider: () => new Date(),
  })
  at!: Date;

  @attribute({ memberType: embed(MatchEventBase), valueConstructor: MatchEventBase })
  //@attribute({ memberType: embed(MatchEventBase) })
  events: Array<MatchEventBase> = [];

  //-- do not persist, this is the initial state for handling events
  //-- when new move is created, before first event is added
  initialState: MatchState;

  constructor(matchId?: MatchId, initialState?: MatchState) {
    this.matchId = matchId;
    this.initialState = initialState;
  }

  get state(): MatchState {
    return this.lastEvent?.state ?? this.initialState;
  }
  get lastEvent(): MatchEventBase {
    return this.events?.at(-1);
  }
  get currentPlayerIndex(): number {
    return this.state?.currentPlayerIndex;
  }
  getEvents(): Array<MatchEventBase> {
    return this.events;
  }
  addEvent(event: MatchEventBase): void {
    this.events?.push(event);
  }
}
