import {
  attribute,
  hashKey,
  autoGeneratedHashKey,
  rangeKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";

export type PlayerId = string;

@table("Players")
export default class Player {
  @autoGeneratedHashKey()
  id!: PlayerId;

  @attribute()
  name!: string;

  constructor(id?: PlayerId, name?: string) {
    this.id = id;
    this.name = name;
  }
}
