/**
 * SLCEE-2023-PC Arena
 * **SAP Labs CEE Hub Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLCEE-2023-PC-public](https://github.com/afarago/SLCEE-2023-PC-public).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: DL SLCEE 2023 PC <DL_637A3F6466D808029A65636A@global.corp.sap>
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MatchHeaderFullDTOPlayerdataInner model module.
 * @module model/MatchHeaderFullDTOPlayerdataInner
 * @version 1.0.0
 */
class MatchHeaderFullDTOPlayerdataInner {
    /**
     * Constructs a new <code>MatchHeaderFullDTOPlayerdataInner</code>.
     * @alias module:model/MatchHeaderFullDTOPlayerdataInner
     * @param bankvalue {Number} 
     * @param banksize {Number} 
     */
    constructor(bankvalue, banksize) { 
        
        MatchHeaderFullDTOPlayerdataInner.initialize(this, bankvalue, banksize);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, bankvalue, banksize) { 
        obj['bankvalue'] = bankvalue;
        obj['banksize'] = banksize;
    }

    /**
     * Constructs a <code>MatchHeaderFullDTOPlayerdataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MatchHeaderFullDTOPlayerdataInner} obj Optional instance to populate.
     * @return {module:model/MatchHeaderFullDTOPlayerdataInner} The populated <code>MatchHeaderFullDTOPlayerdataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatchHeaderFullDTOPlayerdataInner();

            if (data.hasOwnProperty('bankvalue')) {
                obj['bankvalue'] = ApiClient.convertToType(data['bankvalue'], 'Number');
            }
            if (data.hasOwnProperty('banksize')) {
                obj['banksize'] = ApiClient.convertToType(data['banksize'], 'Number');
            }
            if (data.hasOwnProperty('winner')) {
                obj['winner'] = ApiClient.convertToType(data['winner'], 'Boolean');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MatchHeaderFullDTOPlayerdataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MatchHeaderFullDTOPlayerdataInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MatchHeaderFullDTOPlayerdataInner.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

MatchHeaderFullDTOPlayerdataInner.RequiredProperties = ["bankvalue", "banksize"];

/**
 * @member {Number} bankvalue
 */
MatchHeaderFullDTOPlayerdataInner.prototype['bankvalue'] = undefined;

/**
 * @member {Number} banksize
 */
MatchHeaderFullDTOPlayerdataInner.prototype['banksize'] = undefined;

/**
 * @member {Boolean} winner
 */
MatchHeaderFullDTOPlayerdataInner.prototype['winner'] = undefined;

/**
 * @member {Boolean} active
 */
MatchHeaderFullDTOPlayerdataInner.prototype['active'] = undefined;






export default MatchHeaderFullDTOPlayerdataInner;

