/**
 * SLCEE-2023-PC Arena
 * **SAP Labs CEE Hub Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLCEE-2023-PC-public](https://github.com/afarago/SLCEE-2023-PC-public).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: DL SLCEE 2023 PC <DL_637A3F6466D808029A65636A@global.corp.sap>
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BoolLikeString from '../model/BoolLikeString';
import ErrorResponse from '../model/ErrorResponse';
import IUserAction from '../model/IUserAction';
import MatchCreateResponse from '../model/MatchCreateResponse';
import MatchCreationParams from '../model/MatchCreationParams';
import MatchDTO from '../model/MatchDTO';
import MatchEventDTO from '../model/MatchEventDTO';

/**
* Game service.
* @module api/GameApi
* @version 1.0.0
*/
export default class GameApi {

    /**
    * Constructs a new GameApi. 
    * @alias module:api/GameApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Creates a new Match
     * Creates a new Match using the supplied parameters, leave empty for a default 'practice' Match.
     * @param {module:model/MatchCreationParams} matchCreationParams Match creation parameters including players, drawpile, discardpile, banks and randomseed
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/MatchCreateResponse} and HTTP response
     */
    createMatchWithHttpInfo(matchCreationParams) {
      let postBody = matchCreationParams;
      // verify the required parameter 'matchCreationParams' is set
      if (matchCreationParams === undefined || matchCreationParams === null) {
        throw new Error("Missing the required parameter 'matchCreationParams' when calling createMatch");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = MatchCreateResponse;
      return this.apiClient.callApi(
        '/api/matches', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Creates a new Match
     * Creates a new Match using the supplied parameters, leave empty for a default 'practice' Match.
     * @param {module:model/MatchCreationParams} matchCreationParams Match creation parameters including players, drawpile, discardpile, banks and randomseed
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/MatchCreateResponse}
     */
    createMatch(matchCreationParams) {
      return this.createMatchWithHttpInfo(matchCreationParams)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Execute an Action for a Match
     * Execute an Action for an existing Match.  Supply the unique match ID and add Action details
     * @param {String} id 
     * @param {module:model/IUserAction} iUserAction Match action execution parameters
     * @param {Object} opts Optional parameters
     * @param {module:model/BoolLikeString} opts.wait optionally waits with timeout executing the action - useful for waiting for other user to finish its action to avoid polling
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/MatchEventDTO>} and HTTP response
     */
    executeActionForMatchWithHttpInfo(id, iUserAction, opts) {
      opts = opts || {};
      let postBody = iUserAction;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling executeActionForMatch");
      }
      // verify the required parameter 'iUserAction' is set
      if (iUserAction === undefined || iUserAction === null) {
        throw new Error("Missing the required parameter 'iUserAction' when calling executeActionForMatch");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'wait': opts['wait']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [MatchEventDTO];
      return this.apiClient.callApi(
        '/api/matches/{id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Execute an Action for a Match
     * Execute an Action for an existing Match.  Supply the unique match ID and add Action details
     * @param {String} id 
     * @param {module:model/IUserAction} iUserAction Match action execution parameters
     * @param {Object} opts Optional parameters
     * @param {module:model/BoolLikeString} opts.wait optionally waits with timeout executing the action - useful for waiting for other user to finish its action to avoid polling
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/MatchEventDTO>}
     */
    executeActionForMatch(id, iUserAction, opts) {
      return this.executeActionForMatchWithHttpInfo(id, iUserAction, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retrieves a Match details
     * Retrieves the details of an existing match.  Supply the unique match ID and receive corresponding match details.
     * @param {String} id The requested Match Id
     * @param {Object} opts Optional parameters
     * @param {module:model/BoolLikeString} opts.waitactive optionally waits with timeout until user becomes active
     * @param {module:model/BoolLikeString} opts.showevents optionally add events associated with the match
     * @param {module:model/BoolLikeString} opts.showdebug 
     * @param {module:model/BoolLikeString} opts.condensed 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/MatchDTO} and HTTP response
     */
    getMatchWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getMatch");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'waitactive': opts['waitactive'],
        'showevents': opts['showevents'],
        'showdebug': opts['showdebug'],
        'condensed': opts['condensed']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MatchDTO;
      return this.apiClient.callApi(
        '/api/matches/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retrieves a Match details
     * Retrieves the details of an existing match.  Supply the unique match ID and receive corresponding match details.
     * @param {String} id The requested Match Id
     * @param {Object} opts Optional parameters
     * @param {module:model/BoolLikeString} opts.waitactive optionally waits with timeout until user becomes active
     * @param {module:model/BoolLikeString} opts.showevents optionally add events associated with the match
     * @param {module:model/BoolLikeString} opts.showdebug 
     * @param {module:model/BoolLikeString} opts.condensed 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/MatchDTO}
     */
    getMatch(id, opts) {
      return this.getMatchWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Return the Busy days for any match exists
     * @param {Object} opts Optional parameters
     * @param {String} opts.at 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<String>} and HTTP response
     */
    getMatchStatisticsBusyDaysWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'at': opts['at']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['String'];
      return this.apiClient.callApi(
        '/api/matches/busydays', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Return the Busy days for any match exists
     * @param {Object} opts Optional parameters
     * @param {String} opts.at 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<String>}
     */
    getMatchStatisticsBusyDays(opts) {
      return this.getMatchStatisticsBusyDaysWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retrieves all Matches
     * Retrieves the details of all Matches.  Players will receive own matches only
     * @param {Object} opts Optional parameters
     * @param {String} opts.at optional filter parameter in the form of ISO date or 'today'
     * @param {module:model/BoolLikeString} opts.active optional filter matches where player is active at
     * @param {String} opts.tags optional filter for tag - comma separated list of values combined with or logic
     * @param {module:model/BoolLikeString} opts.wait optionally waits with timeout for any resulting match - useful for polling when the user receives invite for a new match to avoid polling
     * @param {module:model/BoolLikeString} opts.condensed optional condensed view
     * @param {Number} opts.limit optional set max number of results returned
     * @param {String} opts.offset optional match id offset used for limiting
     * @param {module:model/BoolLikeString} opts.sortasc optional sorting order, default is descending - latest match first
     * @param {String} opts.id optional filter for list of match ids - comma separated list of values combined with or logic
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/MatchDTO>} and HTTP response
     */
    getMatchesWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'at': opts['at'],
        'active': opts['active'],
        'tags': opts['tags'],
        'wait': opts['wait'],
        'condensed': opts['condensed'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sortasc': opts['sortasc'],
        'id': opts['id']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [MatchDTO];
      return this.apiClient.callApi(
        '/api/matches', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retrieves all Matches
     * Retrieves the details of all Matches.  Players will receive own matches only
     * @param {Object} opts Optional parameters
     * @param {String} opts.at optional filter parameter in the form of ISO date or 'today'
     * @param {module:model/BoolLikeString} opts.active optional filter matches where player is active at
     * @param {String} opts.tags optional filter for tag - comma separated list of values combined with or logic
     * @param {module:model/BoolLikeString} opts.wait optionally waits with timeout for any resulting match - useful for polling when the user receives invite for a new match to avoid polling
     * @param {module:model/BoolLikeString} opts.condensed optional condensed view
     * @param {Number} opts.limit optional set max number of results returned
     * @param {String} opts.offset optional match id offset used for limiting
     * @param {module:model/BoolLikeString} opts.sortasc optional sorting order, default is descending - latest match first
     * @param {String} opts.id optional filter for list of match ids - comma separated list of values combined with or logic
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/MatchDTO>}
     */
    getMatches(opts) {
      return this.getMatchesWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
