/**
 * SLCEE-2023-PC Arena
 * **SAP Labs CEE Hub Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLCEE-2023-PC-public](https://github.com/afarago/SLCEE-2023-PC-public).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: DL SLCEE 2023 PC <DL_637A3F6466D808029A65636A@global.corp.sap>
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CardEffectType from './CardEffectType';

/**
 * The MatchHeaderFullDTOTable model module.
 * @module model/MatchHeaderFullDTOTable
 * @version 1.0.0
 */
class MatchHeaderFullDTOTable {
    /**
     * Constructs a new <code>MatchHeaderFullDTOTable</code>.
     * @alias module:model/MatchHeaderFullDTOTable
     * @param discardpile {Number} 
     * @param drawpile {Number} 
     * @param playarea {Number} 
     */
    constructor(discardpile, drawpile, playarea) { 
        
        MatchHeaderFullDTOTable.initialize(this, discardpile, drawpile, playarea);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, discardpile, drawpile, playarea) { 
        obj['discardpile'] = discardpile;
        obj['drawpile'] = drawpile;
        obj['playarea'] = playarea;
    }

    /**
     * Constructs a <code>MatchHeaderFullDTOTable</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MatchHeaderFullDTOTable} obj Optional instance to populate.
     * @return {module:model/MatchHeaderFullDTOTable} The populated <code>MatchHeaderFullDTOTable</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatchHeaderFullDTOTable();

            if (data.hasOwnProperty('discardpile')) {
                obj['discardpile'] = ApiClient.convertToType(data['discardpile'], 'Number');
            }
            if (data.hasOwnProperty('drawpile')) {
                obj['drawpile'] = ApiClient.convertToType(data['drawpile'], 'Number');
            }
            if (data.hasOwnProperty('playarea')) {
                obj['playarea'] = ApiClient.convertToType(data['playarea'], 'Number');
            }
            if (data.hasOwnProperty('effect')) {
                obj['effect'] = CardEffectType.constructFromObject(data['effect']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MatchHeaderFullDTOTable</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MatchHeaderFullDTOTable</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MatchHeaderFullDTOTable.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

MatchHeaderFullDTOTable.RequiredProperties = ["discardpile", "drawpile", "playarea"];

/**
 * @member {Number} discardpile
 */
MatchHeaderFullDTOTable.prototype['discardpile'] = undefined;

/**
 * @member {Number} drawpile
 */
MatchHeaderFullDTOTable.prototype['drawpile'] = undefined;

/**
 * @member {Number} playarea
 */
MatchHeaderFullDTOTable.prototype['playarea'] = undefined;

/**
 * @member {module:model/CardEffectType} effect
 */
MatchHeaderFullDTOTable.prototype['effect'] = undefined;






export default MatchHeaderFullDTOTable;

